# all:
# 	g++ -o pro1 pro1.cpp -lm -fopenmp

#CC=g++
#CPP_FLAGS=-fopenmp -lm


#default:
	#$(CC) $(CPP_FLAGS) -o pro4 pro4.cpp

all:
	g++ -o MultRedu MultRedu.cpp /usr/local/apps/cuda/cuda-10.1/lib64/libOpenCL.so.1.1 -lm -fopenmp -Wno-write-strings


	./MultRedu
